-- Add preset trivia set metadata (questions will be generated by AI)
-- Run this in Supabase SQL Editor

INSERT INTO public.trivia_sets (id, title, description, theme, difficulty, topic, is_preset) VALUES
('a1111111-1111-1111-1111-111111111111', 'Classic Pub Trivia', 'A comprehensive mix of general knowledge perfect for 2 hours of gameplay', 'Classic', 'medium', 'General Knowledge', true),
('b2222222-2222-2222-2222-222222222222', '80s Music Mania', 'Two hours of nostalgic music trivia from the greatest decade', 'Retro', 'medium', 'Music', true),
('c3333333-3333-3333-3333-333333333333', 'Sports Fanatic', 'Challenge sports enthusiasts with 2 hours of athletic trivia', 'Sports', 'hard', 'Sports', true),
('d4444444-4444-4444-4444-444444444444', 'Pop Culture Party', 'Movies, TV, celebrities - 2 hours of entertainment trivia', 'Entertainment', 'easy', 'Pop Culture', true),
('e5555555-5555-5555-5555-555555555555', 'History Buff Challenge', 'Journey through time with 2 hours of historical questions', 'Academic', 'hard', 'History', true)
ON CONFLICT (id) DO NOTHING;
